<?php

namespace App\Models;

use App\Mail\InviteCreated;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;

class Invite extends Model
{
    use CrudTrait, HasFactory;

    protected $fillable = ['campaign_id', 'email', 'token'];

    public function campaign()
    {
        return $this->belongsTo(Campaign::class);
    }

    public function responses()
    {
        return $this->hasMany(Response::class);
    }

    public static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::created(function (Invite $invite) {
            Mail::to($invite->email)->send(new InviteCreated($invite));
        });
    }
}
